### ISSUE TITLE
缺少ERC20合约

### ISSUE THREAD

**Issue by TeslaZhou-Xin** [truffle-box/drizzle-box#102]
![ddddddddddd5-01](https://user-images.githubusercontent.com/55753672/80938554-22a1c400-8e0c-11ea-9695-9b35b7f81c59.png)
![fffffffff0-05-04_13-35-12](https://user-images.githubusercontent.com/55753672/80938557-246b8780-8e0c-11ea-93ca-13ed7e93ade6.png)

**Comment by Soowin** [comment]
Maybe for some reasons you directly downloaded this repository, not by `truffle unbox` command.
To solve this problem, you should manully run `npm install` in the repository root and the 'app' folder.
Hope it helpful!
