### ISSUE TITLE
Error retrieving network ID

### ISSUE THREAD

**Issue by nigeon** [truffle-box/drizzle-box#11]
Clean install with "truffle unbox drizzle".
Modified truffle.js port to my Ganache one (7545).
Contracts compiled and migrated with no errors.

Getting the following errors when launching the app in the browser :(

![captura de pantalla 2018-03-01 a les 17 11 22](https://user-images.githubusercontent.com/1184258/36855401-9ed2bec8-1d73-11e8-9214-d21875681b63.png)

**Comment by danielrea** [comment]
I had the same issue, I've narrowed it down to some of my compiled contracts not having
```
  "networks": {
    "5777": {
      "events": {},
      "links": {},
      "address": "0x8f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f"
    }
near the end
``` 
Is this perhaps a migration issue, or incorrect solidity compiler version?

**Comment by rvenugopal** [comment]
Am facing the same issue?  @danielrea Do you know if there is a resolution?

Thanks

**Comment by andrewdamelio** [comment]
the below worked for me @rvenugopal 
```
rm -rf build
rm -rf node_modules
npm install
truffle compile
truffle migrate
```

**Comment by nigeon** [comment]
Did what @andrewdamelio suggests and was able to load with no errors.
After unlocking Metamask app loaded successfully.

**Comment by rvenugopal** [comment]
Thanks @andrewdamelio That works

**Comment by appkery** [comment]
It didn't work for me. I set the custom RPC on metamask to http://localhost:9454, then it worked.
