### ISSUE TITLE
Box won't run

### ISSUE THREAD

**Issue by nschwermann** [truffle-box/drizzle-box#119]
I am running into two issues when I try to unbox and run this when I run `truffle unbox drizzle` I see several errors, here is the log: https://gist.github.com/nschwermann/2055df48fa22d6757118bcd3421fc244

When I run the command `npm run start` I get the following error:
```

> app@0.1.0 start
> react-scripts start

sh: react-scripts: command not found
```

**Comment by hainsdominic** [comment]
First, you need to install the dependencies by doing `npm install` followed by `npm update`.

**Comment by RacketyWater7** [comment]
I have tried many times the 'truffle unbox drizzle' command but it keeps failing. My system is Ubuntu 64bit. Please take a look, I would really appreciate your help. Thanks a lot.
Here is the logs link:
https://gist.github.com/RacketyWater7/ccafd73a789b1bdefbcf527702f5b057

**Comment by RacketyWater7** [comment]
> I have tried many times the 'truffle unbox drizzle' command but it keeps failing. My system is Ubuntu 64bit, and the IDE is VS Code. Please take a look, I would really appreciate your help. Thanks a lot. Here is the logs link: https://gist.github.com/RacketyWater7/ccafd73a789b1bdefbcf527702f5b057

Inside the above error log, the logs said  that this command failed: npm install && cd app && npm install
So I ran this command after that, and it also created errors. Here is the log file for that:
https://gist.github.com/RacketyWater7/d2d5dfa1f1e498ce9b4fc38746337046
