### ISSUE TITLE
Issue when running 'npm install' in app directory

### ISSUE THREAD

**Issue by SirMixalotMixalot** [truffle-box/drizzle-box#120]
After running `truffle unbox drizzle`, `cd app` and `npm install` I get these errors

> npm ERR! code 1
> npm ERR! path C:\Users\bk\learn\drizzle_my_nizzle\app\node_modules\sha3
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
> npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
> npm ERR!   addon.cpp
> npm ERR! C:\Users\bk\AppData\Local\node-gyp\Cache\16.5.0\include\node\node.h(63,10): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [C:\Users\bk\learn\drizzle_my_nizzle\app\node_modules\sha3\build\sha3.vcxproj]
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@7.1.2
> npm ERR! gyp info using node@16.5.0 | win32 | x64
> npm ERR! gyp info find Python using Python version 3.9.9 found at "C:\Users\bk\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
> npm ERR! gyp info find VS using VS2019 (16.11.31911.196) found at:
> npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
> npm ERR! gyp info find VS run with --verbose for detailed information
> npm ERR! (node:19196) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
> npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
> npm ERR! gyp info spawn C:\Users\bk\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   'C:\\Users\\bk\\AppData\\Roaming\\nvm\\v16.5.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',
> npm ERR! gyp info spawn args   'msvs',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\bk\\learn\\drizzle_my_nizzle\\app\\node_modules\\sha3\\build\\config.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\bk\\AppData\\Roaming\\nvm\\v16.5.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\bk\\AppData\\Local\\node-gyp\\Cache\\16.5.0\\include\\node\\common.gypi',
> npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
> npm ERR! gyp info spawn args   '-Dvisibility=default',
> npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\bk\\AppData\\Local\\node-gyp\\Cache\\16.5.0',
> npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\bk\\AppData\\Roaming\\nvm\\v16.5.0\\node_modules\\npm\\node_modules\\node-gyp',
> npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\bk\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.5.0\\\\<(target_arch)\\\\node.lib',
> npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\bk\\learn\\drizzle_my_nizzle\\app\\node_modules\\sha3',
> npm ERR! gyp info spawn args   '-Dnode_engine=v8',
> npm ERR! gyp info spawn args   '--depth=.',
> npm ERR! gyp info spawn args   '--no-parallel',
> npm ERR! gyp info spawn args   '--generator-output',
> npm ERR! gyp info spawn args   'C:\\Users\\bk\\learn\\drizzle_my_nizzle\\app\\node_modules\\sha3\\build',
> npm ERR! gyp info spawn args   '-Goutput_dir=.'
> npm ERR! gyp info spawn args ]
> npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   'build/binding.sln',
> npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
> npm ERR! gyp info spawn args   '/nologo',
> npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
> npm ERR! gyp info spawn args ]
> npm ERR! gyp ERR! build error
> npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
> npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\bk\AppData\Roaming\nvm\v16.5.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
> npm ERR! gyp ERR! System Windows_NT 10.0.19041
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bk\\AppData\\Roaming\\nvm\\v16.5.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd C:\Users\bk\learn\drizzle_my_nizzle\app\node_modules\sha3
> npm ERR! gyp ERR! node -v v16.5.0
> npm ERR! gyp ERR! node-gyp -v v7.1.2
> npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\bk\AppData\Local\npm-cache\_logs\2021-12-15T11_39_48_850Z-debug.log
It looks to be an issue with sha3 but I'm unsure as to what the issue could actually be

### NPM version
- 7.19.1
- Nodejs : 16.5.0
- using nvm-windows (running windows 10)

[log file](https://github.com/truffle-box/drizzle-box/files/7719047/2021-12-15T11_39_48_850Z-debug.log)

**Comment by DanubioBlu** [comment]
same error
