### ISSUE TITLE
How Do I listen for events? And how do I catch them?

### ISSUE THREAD

**Issue by andrisole92** [truffle-box/drizzle-box#13]
Example does not show how to use them, any help?

**Comment by diericx** [comment]
I just ran into this too. There's no documentation on how to catch events, it only tells you how to specify certain events to listen for in the config. Could anyone point us in the right direction for this?

**Comment by LoomiDigital** [comment]
Any luck with this? 

I'm using Metamask which doesn't support websockets so I'm unable to use the traditional web3 events

**Comment by manaseepm** [comment]
Would really use some guidance with this. Haven't been able to figure out where and how to watch the emitted event from the contract.

**Comment by chidg** [comment]
As above, this seems like an important thing I would like to know about.
