### ISSUE TITLE
Incompatible with Metamask?

### ISSUE THREAD

**Issue by rvenugopal** [truffle-box/drizzle-box#14]
I was able to get drizzle-box working after I follow the instructions on #11 .
However, I notice that if I have the Metamask extension installed on my browser, then the app does not load for me (just get the loading container).  If I uninstall Metamask, it works.

Tested on Chrome & firefox

Thanks
Rv

**Comment by adrianmcli** [comment]
You need to select the localhost:8545 network on MetaMask and also login with the credentials provided by Ganache. If you are starting out, it's easier to not touch MetaMask until a bit later.
