### ISSUE TITLE
Remove superfluous components

### ISSUE THREAD

**Issue by djudjuu** [truffle-box/drizzle-box#25]
There are lot of unused components in the box, such as .`/src/user/*` and `./src/layouts/dashboard`, and `./src/layouts/home/Home.bak.js`.

If those are neccessary for something, I haven't found out what yet. But if they aren't, (imo) this box would be more elegant (and helpful) if it only contained the bare minimum.

**Comment by nharlow89** [comment]
Just adding to this, looks like there are some things left around from `create-react-app` that can be removed. Ex: `scripts/start.js`:
```js
// You can safely remove this after ejecting.
// We only use this block for testing of Create React App itself:
var isSmokeTest = process.argv.some(arg => arg.indexOf('--smoke-test') > -1);
if (isSmokeTest) {
  handleCompile = function (err, stats) {
    if (err || stats.hasErrors() || stats.hasWarnings()) {
      process.exit(1);
    } else {
      process.exit(0);
    }
  };
}
```

**Comment by cwang25** [comment]
Tried to use Home.bak.js   but seems changing references in HomeContainer is not working.  (something doesn't work well in Home.bak.js        Is Home.bak.js  deprecated ?
