### ISSUE TITLE
What should be on http://localhost:3000?

### ISSUE THREAD

**Issue by pengyu** [truffle-box/drizzle-box#26]
I run the following command.

```
truffle unbox drizzle
truffle compile
truffle migrate
npm run start
```

Then I open `http://localhost:3000`, but I see nothing. Is it what I supposed to see?

**Comment by ZakaryCode** [comment]
You should open with MetaMask，choose you private network and create an account，when Dapp is ready. It will display a sample for couple case for you.

**Comment by Nahasean94** [comment]
@ZakaryCode I have chosen the localhost:8545 as the network and I have logged in with my account that I created when I 1st installed metamask a few months ago, but the page reloads and is still blank. Using chrome, windows 10..what am I not doing?

**Comment by chuckbergeron** [comment]
@pengyu As mentioned in #24 if you run `npm update` then re-compile and re-migrate your contracts, it should work then.
