### ISSUE TITLE
Can't access contract data in HomeContainer

### ISSUE THREAD

**Issue by petscheit** [truffle-box/drizzle-box#27]
I'm having issues with getting the contract data from redux. I've changed the HomeContainer to import Home.bak to play around with getting some data by hand, without the components. The problem I'm having is getting the storedData to show up in the state. 

this is my HomeContainer.js:
```
  import Home from './Home.bak'
  import { drizzleConnect } from 'drizzle-react'

  const mapStateToProps = state => {
    console.log(state)
    return {
      accounts: state.accounts,
      SimpleStorage: state.contracts.SimpleStorage,
      TutorialToken: state.contracts.TutorialToken,
      drizzleStatus: state.drizzleStatus
    }
  }

  const HomeContainer = drizzleConnect(Home, mapStateToProps);

  export default HomeContainer
```

When I print the value here, the storedData object is empty. On the flip side, if I check with the redux-devtool, storedData contains the value i'm looking for. 
![image](https://user-images.githubusercontent.com/10947187/38607956-50da6aaa-3d7a-11e8-8081-7b805a9dff0d.png)

Another thing that is confusing me, is the fact that I'm able to get the proper dataKey (0x0) in Home.bak, though I have a feeling that it's the default return value.

**Comment by mi-kas** [comment]
@petscheit How are you accessing the storedData object?

**Comment by mi-kas** [comment]
I found a good explanation here: [https://itnext.io/how-to-use-drizzle-truffle-and-react-to-make-the-best-front-end-for-your-ethereum-dapp-ee09c8e94eae](https://itnext.io/how-to-use-drizzle-truffle-and-react-to-make-the-best-front-end-for-your-ethereum-dapp-ee09c8e94eae)
