### ISSUE TITLE
Blank Page after fresh installation

### ISSUE THREAD

**Issue by Nahasean94** [truffle-box/drizzle-box#35]
I have just learnt about this box and decided to install it, following the instructions on the ReadMe. However when I run `npm start` after all other installation, the `localhost:3000` page is blank. Then as somebody suggested in this issue [#26](https://github.com/truffle-box/drizzle-box/issues/26), I have metamask installed on chrome, and after selecting localhost as the network and creating an account, the page is still blank. What am I missing?
For further reference, I followed all the steps from 1 to 4 in the readme of this repo, to the letter, and they work. Am stuck on step 5. Using windows 10 and chrome

**Comment by chuckbergeron** [comment]
@Nahasean94 As mentioned here #24 if you run `npm update` then re-compile and re-migrate your contracts, it should work then.

**Comment by dannychua** [comment]
@Nahasean94  @chuckbergeron Getting an error after running `npm update`

	npm WARN drizzle-box@1.0.0 No repository field.
	npm WARN drizzle-box@1.0.0 No license field.
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

	+ redux-thunk@2.3.0
	+ react-router@3.2.1
	+ drizzle-react-components@1.1.0
	+ drizzle@1.1.5
	+ drizzle-react@1.1.1
	removed 1 package, updated 5 packages and audited 98394 packages in 8.374s
	found 595 vulnerabilities (9 low, 296 moderate, 288 high, 2 critical)
	  run `npm audit fix` to fix them, or `npm audit` for details

What should I do?

**Comment by vertangelx** [comment]
@Nahasean94  @chuckbergeron Getting an error after running `npm update`

	npm WARN drizzle-box@1.0.0 No repository field.
	npm WARN drizzle-box@1.0.0 No license field.
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

	+ redux-thunk@2.3.0
	+ react-router@3.2.1
	+ drizzle-react-components@1.1.0
	+ drizzle@1.1.5
	+ drizzle-react@1.1.1
	removed 1 package, updated 5 packages and audited 98394 packages in 8.374s
	found 595 vulnerabilities (9 low, 296 moderate, 288 high, 2 critical)
	  run `npm audit fix` to fix them, or `npm audit` for details

What should I do?

**Comment by chuckbergeron** [comment]
@vertangelx That's a different issue, and is due to dependencies which truffle and other packages rely on. I don't believe there is much you can do until those open source libs patch their security vulnerabilities (then you can upgrade to those patched versions).

**Comment by shivamsinha15** [comment]
Right click inspect and goto to console. Are there any errors displayed in your console as you load your page ?
