### ISSUE TITLE
How to get the web3 instance?

### ISSUE THREAD

**Issue by vertangelx** [truffle-box/drizzle-box#37]
I need to perform something using the `web3` instance, like

    this.props.web3.eth.getBalance(address)

Drizzle only provides us with `state.web3.status`, not the `web3` instance itself. However there are some unused files that might be able to help us achieve this in `source/util/web3`.

Any ideas on how we can expose/access the actual `web3` instance?

**Comment by bellaj** [comment]
same here

**Comment by bellaj** [comment]
https://github.com/trufflesuite/drizzle-react/issues/22

**Comment by robtg4** [comment]
Should be this.context.drizzle.web.eth.getBalance(address) - need to make sure that you are passing 'context' variable in constructor - should look like this: 

```
class ComponentName extends Component {
constructor(props, context) {
    super(props)

    /* local state variables */
    this.state = {
      tokenName: '',
      tokenBalance: 0,
    }

    this.handleClose = this.handleClose.bind(this);
    this.handleCloseAgain = this.handleCloseAgain.bind(this);
  }
  ...

}

ComponentName.contextTypes = {
  drizzle: PropTypes.object
}
```
