### ISSUE TITLE
Explanation for `user` folder and related auth modules

### ISSUE THREAD

**Issue by terencechow** [truffle-box/drizzle-box#41]
The user folder appears to completely unused in this drizzle box. Is there any reason for this? Is there any explanation how to hook it up quickly? If not you should probably remove it from the box.

**Comment by adrianmcli** [comment]
Hmm, you're right. I think this truffle box was super ambitious when it was first written. Inclusion of React Router shows that as well. I plan to create a much more minimal truffle box. In the mean time, if you'd like to submit a PR to remove that folder, you are welcome to do so!
