### ISSUE TITLE
package.json needs updating

### ISSUE THREAD

**Issue by mstobie-seequent** [truffle-box/drizzle-box#42]
npm install leaves many unmet dependencies under webpack->watchpak->chokidir.

Why is such an old version of webpack used compared to drizzle react and drizzle react components?

The app also can not be run because the specified web3 version is too old, I made some progress updating to beta.34

I also couldn't run because deepmerge was required but was missing so had to add that.

I can't get this working at all, after npm update compiling doesn't work, and after fixing issues to get it to compile running still gives a blank screen with the error _drizzle.generateContractsInitialState) is not a function.

I was using Solus if it's relevant.

**Comment by barabis** [comment]
Agreed this truffle box needs some urgent attention.

As a workaround I managed to get the box working by setting drizzle to version 1.1.5.

**Comment by stobiema** [comment]
Yeah that's where I ended up too, limiting drizzle to : 1.1.5 is a workaround for now. I also have

"drizzle-react-components": "1.1.0",

though that version isn't shown in npm it works.

**Comment by harmlessdragon** [comment]
I can't even get it to work with the drizzle limitation...might just have to work with  the library separately.

**Comment by fbdigital** [comment]
@harmlessdragon what errors are you getting? 

Did you run npm update after unboxing?

**Comment by elzopauw** [comment]
I changed the package.json devDependencies to this:

    "drizzle": "1.1.5",
    "drizzle-react": "1.1.0",
    "drizzle-react-components": "1.1.0",

And tried npm install, yet I get the following error:

Uncaught TypeError: (0 , _drizzle.generateContractsInitialState) is not a function

**Comment by harmlessdragon** [comment]
@fbdigital yes, I ran npm update. I then got a deepmerge dependency issue. installing that, I then got web3 dependency issues. I've tried limiting it to 1.1.5, but that also led to different issues.

**Comment by mstobie-seequent** [comment]
Sounds like you had react at too higher version still. What do you see from "npm list drizzle"? Make sure you install again after limiting to 1.1.5 if you updated first. And limit all of drizzle, drizzle-react and drizzle-react-components

**Comment by adrianmcli** [comment]
I believe this is fixed in #49

**Comment by mstobie-seequent** [comment]
Cool, is there a repo for the new one?
