### ISSUE TITLE
React-router v4

### ISSUE THREAD

**Issue by vertangelx** [truffle-box/drizzle-box#45]
Why is react-router v3 still being used here? How difficult is it for us to update to react-router v4?

Pulled out the relevant code below, unsure if this is all that will be changed going for v3 to v4.

**packages.json**

    "react-router": "^3.0.2",
    "react-router-redux": "^4.0.7",

**index.js**

    import { Router, Route, IndexRoute, browserHistory } from 'react-router'
    import { syncHistoryWithStore } from 'react-router-redux'

    ReactDOM.render((
        <DrizzleProvider options={drizzleOptions} store={store}>
        <LoadingContainer>
            <Router history={history}>
            <Route path="/" component={App}>
                <IndexRoute component={HomeContainer} />
            </Route>
            </Router>
        </LoadingContainer>
        </DrizzleProvider>
    ),
    document.getElementById('root')
    );

**Comment by maxme** [comment]
The router could be removed completely, it's not used in the example and devs might want to use another one.

**Comment by adrianmcli** [comment]
Router has been completely removed.
