### ISSUE TITLE
TutorialToken->My Balance not updated

### ISSUE THREAD

**Issue by eloudsa** [truffle-box/drizzle-box#46]
Hi

I noticed that if we switch the account from Metamask, the call to "balanceOf" from "TutorialToken" is not properly called while the account's address has changed.

Have you already notice this issue?
If yes, is there a way to properly update the token's balance without a "manual" page refresh?

Thanks,

Said

**Comment by adrianmcli** [comment]
This is a MetaMask issue, have a look at this StackOverflow question: https://ethereum.stackexchange.com/questions/42768/how-can-i-detect-change-in-account-in-metamask
