### ISSUE TITLE
Dapp won't load after basic initialisation

### ISSUE THREAD

**Issue by tidelake** [truffle-box/drizzle-box#48]
Hello, please forgive my newbity on posting issues.

I am following the basic initialisation tutorial on the Truffle site— [https://truffleframework.com/boxes/drizzle](https://truffleframework.com/boxes/drizzle). I get an error I can only begin to describe with a screenshot. The app freezes on the "Loading dapp" junction.
```
node v8.11.3 (LTS)
npm 5.6.0
```
latest truffle and ganache-cli installed last night (Aug 2, 2018). Thank you for any and all help, and of course, for all the free and awesome software.

![screen shot 2018-08-03 at 6 52 16 pm](https://user-images.githubusercontent.com/12180/43670226-0655d06c-974f-11e8-8ecf-a251494c7c93.png)

**Comment by tidelake** [comment]
I wonder if this is relevant...
```
[drizzle (master)]$ node -v
v8.11.3
[drizzle (master)]$ npm -v
5.6.0


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 6.2.0 → 6.3.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯
```

**Comment by adrianmcli** [comment]
This should have been fixed by #44, please try again and close the issue if it has been resolved.

**Comment by janvde** [comment]
Make sure you are connecting to the same port ganache runs on. Also, when using metamask, connect to your local testnet.

**Comment by pors** [comment]
For development, it's fine to connect to Ganache, but in production, we need to rely on MetaMask connecting to mainnet right? Does that actually work?

**Comment by adrianmcli** [comment]
@pors yes it works, but you need to make sure your project is properly [configured](https://truffleframework.com/docs/truffle/reference/configuration#general-options). Also check out this [part](https://truffleframework.com/docs/truffle/advanced/networks-and-app-deployment) of the docs.

**Comment by pors** [comment]
@adrianmcli thanks Adrian. I'll give that a try!

**Comment by joshma91** [comment]
@tidelake are you still having this issue? It's a silly reason, but the instructions in step 4 of the README  were incorrect and would lead to the error you're seeing if you followed the guide and typed `compile` and `migrate` in the same window you ran `ganache-cli`.

**Comment by tidelake** [comment]
@joshma91 I've not used redux/drizzle since then. I'm just working with react & solidity for now. Thank you. Also learned a fair bit about managing nvm/node/npm since then. I may have had 2 or 3 node installations at the time. Now I use only nvm. Thank you.

**Comment by joshma91** [comment]
@tidelake no problem! Thanks for the prompt reply. 
@adrianmcli I think this can be closed now.

**Comment by adrianmcli** [comment]
Great!
