### ISSUE TITLE
ExampleToken is not defined

### ISSUE THREAD

**Issue by freshonline** [truffle-box/drizzle-box#5]
/myproject$ nano ExampleToken.sol
=====================================
pragma solidity ^0.4.18;
import "node_modules/zeppelin-solidity/contracts/token/ERC20/StandardToken.sol";

contract ExampleToken is StandardToken {
string public name = "ExampleToken";
string public symbol = "EGT";
uint public decimals = 18;
uint public INITIAL_SUPPLY = 10000 * (10 ** decimals);

function ExampleToken() {
totalSupply = INITIAL_SUPPLY;
balances[msg.sender] = INITIAL_SUPPLY;
}
}
=======================================
testnet@e3:~/myproject$ truffle console
truffle(development)> var myToken = ExampleToken.deployed();
ReferenceError: ExampleToken is not defined

**Comment by adrianmcli** [comment]
Closed for inactivity.
