### ISSUE TITLE
Impossible to unbox this box on my Mac with the latest version of Node, NPM and Truffle installed

### ISSUE THREAD

**Issue by sarbogast** [truffle-box/drizzle-box#50]
A simple "truffle unbox drizzle" completely fails with a few warnings and 1 error that says:

```
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sarbogast/dev/cryptoseries-react/node_modules/sha3
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN drizzle-box@1.0.0 No description
npm WARN drizzle-box@1.0.0 No repository field.
npm WARN drizzle-box@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sarbogast/.npm/_logs/2018-08-10T07_49_01_296Z-debug.log
```
The complete log file is here: [2018-08-10T07_47_39_922Z-debug.log](https://github.com/truffle-box/drizzle-box/files/2277039/2018-08-10T07_47_39_922Z-debug.log)

**Comment by mdtanrikulu** [comment]
Please try to run `npm rebuild`. It should solve the problem.

**Comment by sarbogast** [comment]
Just tried npm rebuild and it fails miserably with the following logs: 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sarbogast/dev/cryptoseries-react/node_modules/sha3
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

[2018-08-13T02_08_22_243Z-debug.log](https://github.com/truffle-box/drizzle-box/files/2281610/2018-08-13T02_08_22_243Z-debug.log)

It works with the LTS version of NodeJS, so I'm gonna stick with that for now.

**Comment by xhcardoza** [comment]
I have the same problem in MacOS

**Comment by RomanBrodetski** [comment]
Fails as well on MacOS

**Comment by tobyjaguar** [comment]
trying to build this with an ubuntu Vagrant box on a OSX host machine and am getting some build errors. Did this ever get fixed?

**Comment by causztic** [comment]
I am able to run `truffle unbox drizzle` on my MacOS (10.14.1 Mojave).
`python version = 2.7.14`
`node version = 11`

I was unable to unbox with Node v8, but on v11.0.0 it ran fine.

**Comment by moda20** [comment]
this fails on MacOs HS

**Comment by akhiluthappa1** [comment]
Still facing the same error on Mac OS Monterey.

npm ERR! 3 warnings and 1 error generated.
npm ERR! make: *** [Release/obj.target/sha3/src/addon.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.2.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/akhil/drizzle_tutorial/app/node_modules/sha3
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akhil/.npm/_logs/2022-04-11T12_45_35_939Z-debug-0.log

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at Object.installBoxDependencies (/usr/local/Cellar/truffle/5.4.12/libexec/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:139:1)
    at Object.setUpBox (/usr/local/Cellar/truffle/5.4.12/libexec/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /usr/local/Cellar/truffle/5.4.12/libexec/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:183:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/Cellar/truffle/5.4.12/libexec/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.4.12 (core: 5.4.12)
Node v16.14.0
