### ISSUE TITLE
Drizzle-box not working with relative paths

### ISSUE THREAD

**Issue by CRIZN** [truffle-box/drizzle-box#51]
Hey Everyone,

Thanks for all the hard work! One issue that I have been banging my head trying to resolve is that my dapp which is based off the drizzle box will not load unless it is at the root url. 

- I have updated my package.json to set the correct homepage.
- When I build it says "The project was built assuming it is hosted at /wire-forms/. You can control this with the homepage field in your package.json." which is correct.

But the site will not load unless it is at root. 

Does anyone have any ideas?

**Comment by FriendlyUser** [comment]
When I was working with drizzle I remember encountering this issue, I think your homepage field needs to be adjusted, by default it is at '/

```
"repository": {
    "type": "git",
    "url": "https://google.com",
    "homepage": "/"
  },
```
