### ISSUE TITLE
Not working with Metamask 4.14

### ISSUE THREAD

**Issue by stobiewan** [truffle-box/drizzle-box#57]
Tested with metamask 4.13 and everything was fine. Same code on 4.14 and contract data displays never update, they show the refresh icon and after the tx is included in ganache nothing happens. I guess  some message has changed and drizzle never thinks the contract is in sync? But the value stays wrong too.

**Comment by MarkGeeRomano** [comment]
Can't speak to 4.13 @stobiewan since I'm just trying it out with metamask now, but I can confirm it's not updating the data. Using local truffle instance.

**Comment by stobiewan** [comment]
This has already been fixed in most up to date drizzle
