### ISSUE TITLE
'npm run test' fails after unbox

### ISSUE THREAD

**Issue by paulmeier** [truffle-box/drizzle-box#58]
Did unbox then 'npm test' and get this right out the gate. I'm using osx High Sierra 10.13.6

```
FAIL  src/App.test.js

  console.error node_modules/react-dom/cjs/react-dom.development.js:14226
    The above error occurred in the <Route> component:
        in Route (at App.js:16)
        in div (at App.js:15)
        in App (at App.test.js:7)
```

**Comment by FriendlyUser** [comment]
This is potentially a duplicate question, but in getting `npm run test` is important try using the solution offered in another open issue. https://github.com/truffle-box/drizzle-box/issues/10

https://github.com/dleonard00/dapp-starter/commit/ceb9910467984c45f3811d7f948c7f04aa8acf66
