### ISSUE TITLE
Make it work with drizzle-react-components 1.2.1

### ISSUE THREAD

**Issue by honestbonsai** [truffle-box/drizzle-box#72]
`npm build` will fail with `drizzle-react-components` 1.2.1 with this error: 

```
failed to minify the code from this file
```

This is an issue because the following sequence of events that happens when you unbox

1. `truffle unbox drizzle`
1. `npm install`
1. `npm prepare`
1. `npm build`

Not sure why we even need to build in the first place when the user downloads the box for most likely development purposes. 

But regardless, `npm build` will be broken for when the user wants to make a prod build.

**Comment by adrianmcli** [comment]
We should probably rewrite with latest Create-React-App and not eject. I might get to this over the weekend.

**Comment by sbrichards** [comment]
Is this still an issue after @adrianmcli's re-write (https://github.com/truffle-box/drizzle-box/pull/75)? I've been developing out of this box this week, noticed that 1.2.1 is [in the app/package.json](https://github.com/truffle-box/drizzle-box/blob/master/app/package.json) & can `yarn build` without any errors.

**Comment by adrianmcli** [comment]
@sbrichards thanks for the ping, this looks like it should be closed!
