### ISSUE TITLE
Contract not found on network ID

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [truffle-box/drizzle-box#79]
After deploy the contract and start the client, it gave error for not finding contract.

![image](https://user-images.githubusercontent.com/5875315/52108799-cf194880-25c0-11e9-8839-fcb2063db041.png)

**Comment by jgege** [comment]
To see what address a specific contract has on different networks you can open app/src/contracts/YourContractName.json and search for "networks". 

If it's there you can try restarting your test network (I guess you use ganache or truffle develop) and run truffle migrate again.

If it still fails you might have the same issue as I had. For a solution see: https://github.com/truffle-box/drizzle-box/issues/78

**Comment by Xuefeng-Zhu** [comment]
I have resolved the issue. It is due to web3 version
