### ISSUE TITLE
MM friendly truffle-config doesn't work as is

### ISSUE THREAD

**Issue by parkinsonj** [truffle-box/drizzle-box#81]
The name 'develop' causes it to not work. I changed it to 'development' and it worked as expected.

(Blockchain exposed on 127.0.0.1:8545 using ganache-cli)

**Comment by adrianmcli** [comment]
Fixed this in https://github.com/truffle-box/drizzle-box/commit/ebaee389281db9e61ab39a2832e307c0c4447c06

Thanks for reporting @parkinsonj
